name: deploy-pipeline-manual

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: deploy
        run: echo "Deploying to $ENVIRONMENT from $BRANCH branch"
