name: deploy-pipeline-manual

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: deploy
        run: echo "Deploying to $ENVIRONMENT from $GITHUB_HEAD_REF branch"