name: deploy-workflow

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string

jobs:
  environment:
    name: ${{ inputs.ENVIRONMENT }}
  deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: deploy
        run: echo "Deploying to $ENVIRONMENT"
