name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      ENVIRONMENT: staging

  deploy-production:
    uses: ./.github/workflows/deploy-workflow.yml
    needs:
      - deploy-staging
    with:
      ENVIRONMENT: production
